version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - adoptme/.env
  web:
    build: .
    command: sh ./adoptme/entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - adoptme/.env
    depends_on:
      - db

volumes:
  postgres_data: